### ISSUE TITLE
Anonymous or Not Setting

### ISSUE THREAD

**Issue by VOjha** [Up-Next/up-next#13]
When creating a `Party`, the creator should be able to choose whether the username of the person adding the track appears next to the track.

**Comment by VOjha** [comment]
I kind of don't want to put in the work of adding this feature lol

We would have to make the playlist's appearance conditional on this setting, and have a different bootstrap column divide depending on whether it was True or not. It's not super hard but I don't like this feature enough to do it, tbh.

Thoughts? @vsiri @kimberlytze

**Comment by kimberlytze** [comment]
Yeah, I say we ditch it and not display any names
