### ISSUE TITLE
Navigational Buttons

### ISSUE THREAD

**Issue by VOjha** [Up-Next/up-next#29]
We should add some better navigation.

On the `Search Track Results` page:
- [x] Button to go back to `Party Detail` without adding a track (addressed in #60)
- [x] Search bar to change search query (addressed in #37)

On the `Party Search Results` page:
- [x] Each party listed should link to the respective party detail page

**Comment by kimberlytze** [comment]
We can just have the UpNext logo redirect to the index on every page?

**Comment by VOjha** [comment]
Oh lol good point. Updated :+1:
