### ISSUE TITLE
Minimum Score

### ISSUE THREAD

**Issue by VOjha** [Up-Next/up-next#56]
Delete songs below a certain score (-10?) automatically.

**Comment by VOjha** [comment]
Question about this @vsiri @kimberlytze 

The logical way to implement this, IMO, is that every time a downvote occurs, we check if the score is now `-10` (or whatever number), and if it is we delete. But in that case, what if a song is at `-9` and someone accidentally downvotes it? They don't have the chance to fix their vote because the song is gone. What do?

**Comment by kimberlytze** [comment]
Hmmm good question... I say we just delete it and someone can add it back if they really want it? Doesn't make sense to me to check the score (and possibly delete the track) at any other time.
